# Specify a non-default branch for pull requests for pip (poetry)

# See all parameters documented in:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Even if we use poetry, GitHub requires the following value to be `pip` (as of 2023-07-24)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates to pip against the following branch
    target-branch: "develop"

    # "Always increase the minimum version requirement to match the new version. If a range already exists, typically this only increases the lower bound."
    versioning-strategy: "increase"
