[tool.poetry]
name = "website_monitor"
version = "0.1.0"
description = ""
authors = ["Dr. Juan Miguel Cejuela <i@juanmi.rocks>"]
readme = "README.md"
packages = [{include = "website_monitor"}]

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.8.4"


[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
pyflakes = "^3.0.1"
bandit = "^1.7.5"
black = "^23.3.0"
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
